### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by aminya** [atk/solid-blocks#1]
Thanks for this interesting library. I was wondering if you can add documentation for this code to make it easier to use the code

**Comment by atk** [comment]
Thanks for your feedback.

Documentation is already on my Todo list. I first want the components to stabilize before I document them, but I'm only missing 2 more and 1-2 rounds of refactoring until that stage is reached.

**Comment by atk** [comment]
The work just started on this one. Update: I just pushed the first WIP commit. If you have any feedback about the format of the documentation, I would appreciate it.

**Comment by atk** [comment]
Almost finished the first incarnation of the documentation and also published it to github pages.

**Comment by atk** [comment]
This should suffice for a first version of the documentation, I guess.

**Comment by aminya** [comment]
Thanks! :tada:
