### ISSUE TITLE
Plans to add this to npm?

### ISSUE THREAD

**Issue by Skyblueballykid** [atk/solid-blocks#4]
I tried installing this with pnpm install solid-blocks and it doesn't seem to be on the NPM registry. Do you have plans to support it there, or do I have the incorrect package name?

**Comment by atk** [comment]
It's definitely in the plans once I finished my other todos to get this to a releasable state.

**Comment by Skyblueballykid** [comment]
Looking forward to it!

**Comment by atk** [comment]
It already is on npm
